;Menu principal
m  db '------- M E N U ------$'
m1 db '1. Programa letra de una cancion $'
m2 db '2. Programa encuesta $'
m3 db '3. Programa receta medica $'
m4 db '4. Programa gato $'
m5 db '5. Programa operaciones $'
m6 db '6. Programa tabla de multiplicar $'
m7 db '7. Salir$'
;Respuesta
opc  db 'Desea volver al menu principal SI(1) NO(0):  $'
opc1 db 'Seleccione una opcion: $'
opc2 db 'Hacer otra tabla SI(1) NO(2) Volver al menu anterior(3): $'
res  db 1 dup (' '), '$'
;Titulos
ti1 db '------- Letra cancion-------$'
ti2 db '------- Encuesta -------$'
ti3 db '------- Receta Medica -------$'
ti4 db '------- Gato -------$'
ti5 db '------- Operaciones -------$'
ti6 db '------- Tabla de multiplicar ------$'
;Programa 1
msg   db 'Solamente quiero amarte$'
msg1  db 'Y todo mi calor brindarte$'
msg2  db 'Te hare olvidar esa penas que te hacen mal$'
msg3  db 'Hay que dar el sentimiento$'
msg4  db 'Y cada momento vivirlo$'
msg5  db 'Te hare olvidar esas penas que te hacen mal$'
msg6  db 'Con el amor$'
msg7  db 'Se puede siempre alcanzar lo mejor$'
msg8  db 'Con el amor$'
msg9  db 'Los suenos que tengas se van a cumplir$'
msg10 db 'Si tu lo deseas puedes volar$'
msg11 db 'Solo tienes que confiar$'
msg12 db 'Mucho en ti y seguir$'
msg13 db 'Puedes contar conmigo te doy todo mi apoyo$'
msg14 db 'Si tu lo deseas puedes volar$'
msg15 db 'Si tu quieres el cielo alcanzar$'
msg16 db 'Y las estrellas tocar$'
msg17 db 'Digimon$'
;Programa 2
msgPregunta1     db 'Cual es tu nombre? $'
msgPregunta2     db 'Cuantos minutos tiene una hora? $'
msgPregunta3     db 'Cuantos años tienes? $'
msgPregunta4     db 'Cual es tu color favorito? $'
msgPregunta5     db 'Cual es tu serie favorita? $'
msgPregunta6     db 'Marvel o DC? $'
msgPregunta7     db 'Sony, XBOX o Nintendo? $'
msgPregunta8     db 'Musica favorita? $'
msgPregunta9     db 'Consola favorita? $'
msgPregunta10    db 'Te gusta el anime? $'
resmsgPregunta1  db 'Tu nombre es: ','$'
resmsgPregunta2  db 'Los minutos en una hora son: ','$'
resmsgPregunta3  db 'Tu edad es: ','$'
resmsgPregunta4  db 'Tu color favorito es: ','$'
resmsgPregunta5  db 'Tu serie favorita es: ','$'
resmsgPregunta6  db 'Prefieres: ','$'
resmsgPregunta7  db 'Prefieres: ','$'
resmsgPregunta8  db 'Tu musica favorita es: ','$'
resmsgPregunta9  db 'Tu consola favorita es: ','$'
resmsgPregunta10 db 'Te gusta el anime: ','$'
resPregunta1     db 50 dup(' '),'$'
resPregunta2     db 50 dup(' '),'$'
resPregunta3     db 50 dup(' '),'$'
resPregunta4     db 50 dup(' '),'$'
resPregunta5     db 50 dup(' '),'$'
resPregunta6     db 50 dup(' '),'$'
resPregunta7     db 50 dup(' '),'$'
resPregunta8     db 50 dup(' '),'$'
resPregunta9     db 50 dup(' '),'$'
resPregunta10    db 50 dup(' '),'$'
;Programa 3
rec   db '+----------+---------------------------+------------------------+------------+$'
rec1  db '|          |Consulta ficha del paciente|                        |            |$'
rec2  db '+----------+---------------------------+-------------------------------------+$'
rec3  db '|Apellidos |                           |Nombres  |                           |$'
rec4  db '+----------+---------------------------+---------+---------------------------+$'
rec5  db '|Direccion |                           |C.Postal |                           |$'
rec6  db '+----------+---------------------------+---------+---------------------------+$'
rec7  db '|Localidad |                           |provincia|                           |$'
rec8  db '+----------------------------------------------------------------------------+$'
rec9  db '|F.Nacimiento|              |Sexo|    |NSS|           |TEL.|                 |$'
rec10 db '+----------------------------------------------------------------------------+$'
rec11 db '|F.Consulta|                |F.Alta|           |Duracion Proceso|            |$'
rec12 db '+----------------------------------------------------------------------------+$'
rec13 db '|Diagnostico|                                                                |$'
rec14 db '+----------------------------------------------------------------------------+$'
rec15 db '|Tratamiento|                                                                |$'
rec16 db '+----------------------------------------------------------------------------+$'
rec17 db '|Otros datos|                                                                |$'
rec18 db '+----------------------------------------------------------------------------+$'
rec19 db '|Observaciones|                                                              |$'
rec20 db '+----------------------------------------------------------------------------+$'
;espacios para respuestas
re01 db 30 dup ('  '), '$'
re02 db 15 dup ('  '), '$'
re03 db 15 dup ('  '), '$'
re04 db 15 dup ('  '), '$'
re05 db 15 dup ('  '), '$'
re06 db 15 dup ('  '), '$'
re07 db 15 dup ('  '), '$'
re08 db 15 dup ('  '), '$'
re09 db 15 dup ('  '), '$'
re10 db 15 dup ('  '), '$'
re11 db 15 dup ('  '), '$'
re12 db 15 dup ('  '), '$'
re13 db 15 dup ('  '), '$'
re14 db 15 dup ('  '), '$'
re15 db 15 dup ('  '), '$'
re16 db 15 dup ('  '), '$'
re17 db 15 dup ('  '), '$'
re18 db 15 dup ('  '), '$'
;Programa 4
gt0  db 'EL JUEGO DEL$'
gt1  db '####  ####  ####  ####$'
gt2  db '#     #  #   ##   #  #$'
gt3  db '# ##  ####   ##   #  #$'
gt4  db '#  #  #  #   ##   #  #$'
gt5  db '####  #  #   ##   ####$'
gt6  db ' |   |$'
gt7  db ' 1 | 2 | 3 $'
gt8  db '---+---+---$'
gt9  db '|   |$'
gt10 db ' 4 | 5 | 6 $'
gt11 db '---+---+---$'
gt12 db ' 7 | 8 | 9 $'
gt13 db '|   |$'
gt14 db 'Jugadores$'
gt15 db '==> X -Genaro$'
gt16 db '==> O -Damian$'
gt17 db ' ------------- $'
gt18 db '| Bienvenidos |$'
gt19 db ' -------------  |$'
gt20 db '   ------------  $'
;programa 5
s0 db 'Ingrese un numero: $'
s1 db 'El resultado de la suma es: $'
s2 db 'El resultado de la resta es: $'
s3 db 'El resultado de la multiplicacion es: $'
s4 db 'El resultado de la division es: $'
n1 db 0
n2 db 0
sum db 0
re db 0
multi db 0
divi db 0
;Programa 6
t0 db 'Que tabla desea mostrar? $'
n db 0
r db 0
conta db 0

