men    db '------- MENU -------$'
men1   db ' 1. Cadena  1  $'
men2   db ' 2. Cadena  2  $'
men3   db ' 3. Cadena  3  $'
men4   db ' 4. Cadena  4  $'
men5   db ' 5. Cadena  5  $'
men6   db ' 6. Cadena  6  $'
men7   db ' 7. Cadena  7  $'
men8   db ' 8. Cadena  8  $'
men9   db ' 9. Cadena  9  $'
men10  db ' 0. Cadena 10  $'
men11  db 'ESC. Salir $'
;---
cad0   db 'Usted eligio $'
cad1   db ' Cadena  1  $'
cad2   db ' Cadena  2  $'
cad3   db ' Cadena  3  $'
cad4   db ' Cadena  4  $'
cad5   db ' Cadena  5  $'
cad6   db ' Cadena  6  $'
cad7   db ' Cadena  7  $'
cad8   db ' Cadena  8  $'
cad9   db ' Cadena  9  $'
cad10  db ' Cadena 10  $'
;---
opc   db 'Desea volver al menu principal? SI(1) NO(0): $'
opc1  db 'Seleccione una opcion: $'
res   db 1 dup (' '), '$'

 